version: '3.4'

networks:
  trackmate_network:
    driver: bridge

services:
  trackmate:
    ports:
        - 7195:443
    image: ${DOCKER_REGISTRY-}trackmate
    build:
      context: .
      dockerfile: TrackMate/Dockerfile
    depends_on:
        - trackmate.api
    networks:
        - trackmate_network

  trackmate.api:
    container_name: api
    image: ${DOCKER_REGISTRY-}trackmateapi
    build:
      context: .
      dockerfile: TrackMate.Api/Dockerfile
    networks:
        - trackmate_network

