version: '3.4'

networks:
  trackmate_network:
    driver: bridge

services:
  trackmate:
    ports:
        - 7195:443
        - 5137:80
    image: shalinisaravanan/app:latest
    networks:
        - trackmate_network
    volumes:
      - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "7195"
      ASPNETCORE_ENVIRONMENT: "Development"

  trackmate.api:
    container_name: api
    image: shalinisaravanan/api:latest
    networks:
        - trackmate_network

